# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependenci/welome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflowme"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
